export const seznam = [
  {
    jmeno: 'Jan',
    prijmeni: 'Svoboda',
    pohlavi: 0,
    bystrost: 4,
    samostatnost: 3,
    socialni: 2,
  },
  {
    jmeno: 'Marie',
    prijmeni: 'Nováková',
    pohlavi: 1,
    bystrost: 5,
    samostatnost: 4,
    socialni: 5,
  },
  {
    jmeno: 'Petr',
    prijmeni: 'Dvořák',
    pohlavi: 0,
    bystrost: 3,
    samostatnost: 2,
    socialni: 3,
  },
  {
    jmeno: 'Anna',
    prijmeni: 'Jelínková',
    pohlavi: 1,
    bystrost: 4,
    samostatnost: 5,
    socialni: 4,
  },
  {
    jmeno: 'Tomáš',
    prijmeni: 'Kučera',
    pohlavi: 0,
    bystrost: 2,
    samostatnost: 3,
    socialni: 1,
  },
  {
    jmeno: 'Lucie',
    prijmeni: 'Černá',
    pohlavi: 1,
    bystrost: 5,
    samostatnost: 2,
    socialni: 5,
  },
  {
    jmeno: 'Martin',
    prijmeni: 'Procházka',
    pohlavi: 0,
    bystrost: 3,
    samostatnost: 4,
    socialni: 3,
  },
  {
    jmeno: 'Tereza',
    prijmeni: 'Horáková',
    pohlavi: 1,
    bystrost: 4,
    samostatnost: 5,
    socialni: 2,
  },
  {
    jmeno: 'Filip',
    prijmeni: 'Marek',
    pohlavi: 0,
    bystrost: 1,
    samostatnost: 1,
    socialni: 4,
  },
  {
    jmeno: 'Kateřina',
    prijmeni: 'Růžičková',
    pohlavi: 1,
    bystrost: 5,
    samostatnost: 3,
    socialni: 5,
  },
  {
    jmeno: 'Daniel',
    prijmeni: 'Fiala',
    pohlavi: 0,
    bystrost: 4,
    samostatnost: 2,
    socialni: 1,
  },
  {
    jmeno: 'Eliška',
    prijmeni: 'Benešová',
    pohlavi: 1,
    bystrost: 3,
    samostatnost: 4,
    socialni: 2,
  },
  {
    jmeno: 'Matěj',
    prijmeni: 'Konečný',
    pohlavi: 0,
    bystrost: 2,
    samostatnost: 5,
    socialni: 3,
  },
  {
    jmeno: 'Veronika',
    prijmeni: 'Pospíšilová',
    pohlavi: 1,
    bystrost: 5,
    samostatnost: 4,
    socialni: 1,
  },
  {
    jmeno: 'Jakub',
    prijmeni: 'Sedláček',
    pohlavi: 0,
    bystrost: 3,
    samostatnost: 1,
    socialni: 5,
  },
  {
    jmeno: 'Michaela',
    prijmeni: 'Šimková',
    pohlavi: 1,
    bystrost: 4,
    samostatnost: 3,
    socialni: 4,
  },
  {
    jmeno: 'Lukáš',
    prijmeni: 'Kadlec',
    pohlavi: 0,
    bystrost: 5,
    samostatnost: 5,
    socialni: 2,
  },
  {
    jmeno: 'Kristýna',
    prijmeni: 'Kratochvílová',
    pohlavi: 1,
    bystrost: 2,
    samostatnost: 2,
    socialni: 3,
  },
  {
    jmeno: 'Adam',
    prijmeni: 'Rybář',
    pohlavi: 0,
    bystrost: 4,
    samostatnost: 1,
    socialni: 2,
  },
  {
    jmeno: 'Nikola',
    prijmeni: 'Veselá',
    pohlavi: 1,
    bystrost: 3,
    samostatnost: 3,
    socialni: 5,
  },
  {
    jmeno: 'Vojtěch',
    prijmeni: 'Král',
    pohlavi: 0,
    bystrost: 5,
    samostatnost: 4,
    socialni: 4,
  },
  {
    jmeno: 'Barbora',
    prijmeni: 'Doležalová',
    pohlavi: 1,
    bystrost: 1,
    samostatnost: 2,
    socialni: 1,
  },
  {
    jmeno: 'Ondřej',
    prijmeni: 'Kolář',
    pohlavi: 0,
    bystrost: 4,
    samostatnost: 3,
    socialni: 3,
  },
  {
    jmeno: 'Karolína',
    prijmeni: 'Zemanová',
    pohlavi: 1,
    bystrost: 3,
    samostatnost: 5,
    socialni: 2,
  },
];
