export const seznam = [
  {
    celeJmeno: 'Jan Svoboda',
    pohlavi: 0,
    bystrost: 4,
    samostatnost: 3,
    socialni: 2,
    trida: "1A",
  },
  {
    celeJmeno: 'Marie Nováková',
    pohlavi: 1,
    bystrost: 5,
    samostatnost: 4,
    socialni: 5,
    trida: "2A",
  },
  {
    celeJmeno: 'Petr Dvořák',
    pohlavi: 0,
    bystrost: 3,
    samostatnost: 2,
    socialni: 3,
    trida: "1A",
  },
  {
    celeJmeno: 'Anna Jelínková',
    pohlavi: 1,
    bystrost: 4,
    samostatnost: 5,
    socialni: 4,
    trida: "2A",
  },
  {
    celeJmeno: 'Tomáš Kučera',
    pohlavi: 0,
    bystrost: 2,
    samostatnost: 3,
    socialni: 1,
    trida: "1A",
  },
  {
    celeJmeno: 'Lucie Černá',
    pohlavi: 1,
    bystrost: 5,
    samostatnost: 2,
    socialni: 5,
    trida: "2A",
  },
  {
    celeJmeno: 'Martin Procházka',
    pohlavi: 0,
    bystrost: 3,
    samostatnost: 4,
    socialni: 3,
    trida: "1A",
  },
  {
    celeJmeno: 'Tereza Horáková',
    pohlavi: 1,
    bystrost: 4,
    samostatnost: 5,
    socialni: 2,
    trida: "2A",
  },
  {
    celeJmeno: 'Filip Marek',
    pohlavi: 0,
    bystrost: 1,
    samostatnost: 1,
    socialni: 4,
    trida: "1A",
  },
  {
    celeJmeno: 'Kateřina Růžičková',
    pohlavi: 1,
    bystrost: 5,
    samostatnost: 3,
    socialni: 5,
    trida: "2A",
  },
  {
    celeJmeno: 'Daniel Fiala',
    pohlavi: 0,
    bystrost: 4,
    samostatnost: 2,
    socialni: 1,
    trida: "1A",
  },
  {
    celeJmeno: 'Eliška Benešová',
    pohlavi: 1,
    bystrost: 3,
    samostatnost: 4,
    socialni: 2,
    trida: "2A",
  },
  {
    celeJmeno: 'Matěj Konečný',
    pohlavi: 0,
    bystrost: 2,
    samostatnost: 5,
    socialni: 3,
    trida: "1A",
  },
  {
    celeJmeno: 'Veronika Pospíšilová',
    pohlavi: 1,
    bystrost: 5,
    samostatnost: 4,
    socialni: 1,
    trida: "2A",
  },
  {
    celeJmeno: 'Jakub Sedláček',
    pohlavi: 0,
    bystrost: 3,
    samostatnost: 1,
    socialni: 5,
    trida: "1A",
  },
  {
    celeJmeno: 'Michaela Šimková',
    pohlavi: 1,
    bystrost: 4,
    samostatnost: 3,
    socialni: 4,
    trida: "2A",
  },
  {
    celeJmeno: 'Lukáš Kadlec',
    pohlavi: 0,
    bystrost: 5,
    samostatnost: 5,
    socialni: 2,
    trida: "1A",
  },
  {
    celeJmeno: 'Kristýna Kratochvílová',
    pohlavi: 1,
    bystrost: 2,
    samostatnost: 2,
    socialni: 3,
    trida: "2A",
  },
  {
    celeJmeno: 'Adam Rybář',
    pohlavi: 0,
    bystrost: 4,
    samostatnost: 1,
    socialni: 2,
    trida: "1A",
  },
  {
    celeJmeno: 'Nikola Veselá',
    pohlavi: 1,
    bystrost: 3,
    samostatnost: 3,
    socialni: 5,
    trida: "2A",
  },
  {
    celeJmeno: 'Vojtěch Král',
    pohlavi: 0,
    bystrost: 5,
    samostatnost: 4,
    socialni: 4,
    trida: "1A",
  },
  {
    celeJmeno: 'Barbora Doležalová',
    pohlavi: 1,
    bystrost: 1,
    samostatnost: 2,
    socialni: 1,
    trida: "2A",
  },
  {
    celeJmeno: 'Ondřej Kolář',
    pohlavi: 0,
    bystrost: 4,
    samostatnost: 3,
    socialni: 3,
    trida: "1A",
  },
  {
    celeJmeno: 'Karolína Zemanová',
    pohlavi: 1,
    bystrost: 3,
    samostatnost: 5,
    socialni: 2,
    trida: "2A",
  },
];
